modLoader="javafml"
loaderVersion="[32,)"
license="MIT"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.aewirelesschannel]]
modId="appliedenergistics2"
mandatory=true
versionRange="[8.4.0,)"
ordering="AFTER"
side="BOTH"

[[dependencies.aewirelesschannel]]
modId="theoneprobe"
mandatory=false
versionRange="[1.16-3.0.0,1.16-4.0.0)"
ordering="AFTER"
side="BOTH"
